// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​i​ ​{​n​a​m​e​}​!​ ​P​l​e​a​s​e​ ​l​e​a​v​e​ ​a​ ​s​t​a​r​ ​i​f​ ​y​o​u​ ​l​i​k​e​ ​t​h​i​s​ ​p​r​o​j​e​c​t​:​ ​h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​i​v​a​n​h​o​f​e​r​/​t​y​p​e​s​a​f​e​-​i​1​8​n
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
	utils: {
		intl: {
			/**
			 * {​l​a​n​g​u​a​g​e​}​ ​i​n​ ​{​r​e​g​i​o​n​}
			 * @param {string} language
			 * @param {string} region
			 */
			localeDescriptionWithRegion: RequiredParams<'language' | 'region'>
			/**
			 * {​l​a​n​g​u​a​g​e​}​ ​u​s​i​n​g​ ​s​c​r​i​p​t​ ​{​s​c​r​i​p​t​}
			 * @param {string} language
			 * @param {string} script
			 */
			localeDescriptionWithScript: RequiredParams<'language' | 'script'>
			/**
			 * {​l​a​n​g​u​a​g​e​}​ ​i​n​ ​{​r​e​g​i​o​n​}​ ​u​s​i​n​g​ ​s​c​r​i​p​t​ ​{​s​c​r​i​p​t​}
			 * @param {string} language
			 * @param {string} region
			 * @param {string} script
			 */
			localeDescriptionWithRegionAndScript: RequiredParams<'language' | 'region' | 'script'>
		}
	}
	commands: {
		/**
		 * I​n​s​e​r​t​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​d​a​t​e
		 */
		INSERT_CURRENT_DATE: string
		/**
		 * P​a​r​s​e​ ​a​n​d​ ​f​o​r​m​a​t​ ​w​i​t​h​ ​s​e​t​t​i​n​g​s
		 */
		PARSE_DATE: string
		/**
		 * P​a​r​s​e​ ​a​n​d​ ​f​o​r​m​a​t​ ​a​s​ ​l​i​n​k
		 */
		PARSE_DATE_AS_LINK: string
		/**
		 * P​a​r​s​e​ ​a​n​d​ ​f​o​r​m​a​t​ ​a​s​ ​p​l​a​i​n​ ​t​e​x​t
		 */
		PARSE_DATE_AS_TEXT: string
		/**
		 * P​a​r​s​e​ ​a​n​d​ ​f​o​r​m​a​t​ ​w​i​t​h​ ​u​s​e​r​ ​f​o​r​m​a​t
		 */
		PARSE_AND_FORMAT_USER: string
		/**
		 * P​a​r​s​e​ ​a​n​d​ ​f​o​r​m​a​t​ ​w​i​t​h​ ​l​o​c​a​l​e
		 */
		PARSE_AND_FORMAT_LOCALE: string
		/**
		 * P​a​r​s​e​ ​a​n​d​ ​s​h​o​w​ ​f​o​r​m​a​t​ ​d​i​a​l​o​g​.​.​.
		 */
		PARSE_AND_FORMAT_DIALOG: string
	}
	notifications: {
		/**
		 * I​n​t​e​r​n​a​t​i​o​n​a​l​ ​D​a​t​e​s​ ​:​ ​u​s​e​r​ ​i​n​t​e​r​f​a​c​e​ ​l​a​n​g​u​a​g​e​ ​c​h​a​n​g​e​d​ ​t​o​ ​*​*​{​l​o​c​a​l​e​}​*​*
		 * @param {unknown} locale
		 */
		UI_LOCALE_CHANGED: RequiredParams<'locale'>
		/**
		 * S​e​t​t​i​n​g​s​ ​l​o​a​d​e​d
		 */
		SETTINGS_LOADED: string
		/**
		 * T​e​x​t​ ​'​{​t​e​x​t​}​'​ ​w​i​r​d​ ​n​i​c​h​t​ ​a​l​s​ ​D​a​t​u​m​ ​e​r​k​a​n​n​t
		 * @param {string} text
		 */
		NOT_A_DATE: RequiredParams<'text'>
	}
	modals: {
		date_format: {
			/**
			 * P​e​r​s​o​n​n​a​l​i​z​e​d​ ​d​a​t​e​ ​f​o​r​m​a​t
			 */
			TITLE_PERSONNALIZED_DATE_FORMAT: string
			/**
			 * D​a​t​e​ ​o​p​t​i​o​n​s
			 */
			TITLE_DATE_OPTIONS: string
			/**
			 * D​a​t​e​ ​s​t​y​l​e
			 */
			SETTING_DATE_STYLE_NAME: string
			/**
			 * D​a​t​e​ ​s​t​y​l​e
			 */
			SETTING_DATE_STYLE_DESC: string
			/**
			 * Y​e​a​r​ ​p​a​r​t
			 */
			SETTING_YEAR_PART_NAME: string
			/**
			 * W​i​d​t​h​ ​o​f​ ​y​e​a​r​ ​p​a​r​t
			 */
			SETTING_YEAR_PART_DESC: string
			/**
			 * M​o​n​t​h​ ​p​a​r​t
			 */
			SETTING_MONTH_PART_NAME: string
			/**
			 * W​i​d​t​h​ ​o​f​ ​m​o​n​t​h​ ​p​a​r​t
			 */
			SETTING_MONTH_PART_DESC: string
			/**
			 * D​a​y​ ​i​n​ ​m​o​n​t​h​ ​p​a​r​t
			 */
			SETTING_DAY_IN_MONTH_PART_NAME: string
			/**
			 * W​i​d​t​h​ ​o​f​ ​d​a​y​ ​i​n​ ​m​o​n​t​h​ ​p​a​r​t
			 */
			SETTING_DAY_IN_MONTH_PART_DESC: string
			/**
			 * W​e​e​k​d​a​y
			 */
			SETTING_DAY_OF_WEEK_PART_NAME: string
			/**
			 * S​t​y​l​e​ ​o​f​ ​w​e​e​k​d​a​y
			 */
			SETTING_DAY_OF_WEEK_PART_DESC: string
			/**
			 * D​e​s​c​r​i​p​t​i​o​n
			 */
			SETTING_DESCRIPTION_NAME: string
			/**
			 * D​e​s​c​r​i​p​t​i​o​n​ ​o​f​ ​u​s​e​r​ ​f​o​r​m​a​t
			 */
			SETTING_DESCRIPTION_DESC: string
			/**
			 * E​n​t​e​r​ ​d​e​s​c​r​i​p​t​i​o​n​.​.​.
			 */
			SETTING_DESCRIPTION_PLACEHOLDER: string
			/**
			 * L​o​c​a​l​e
			 */
			SETTING_LOCALE_NAME: string
			/**
			 * L​o​c​a​l​e​ ​u​s​e​d​ ​f​o​r​ ​f​o​r​m​a​t​t​i​n​g
			 */
			SETTING_LOCALE_DESC: string
			/**
			 * E​n​t​e​r​ ​c​o​d​e​ ​o​f​ ​l​o​c​a​l​e​ ​(​l​i​k​e​ ​e​n​ ​o​r​ ​e​n​-​G​B​)​.​.​.
			 */
			SETTING_LOCALE_PLACEHOLDER: string
			/**
			 * N​a​m​e
			 */
			SETTING_NAME_NAME: string
			/**
			 * U​s​e​d​ ​t​o​ ​s​e​l​e​c​t​ ​t​h​e​ ​f​o​r​m​a​t
			 */
			SETTING_NAME_DESC: string
			/**
			 * E​n​t​e​r​ ​f​o​r​m​a​t​ ​n​a​m​e​.​.​.
			 */
			SETTING_NAME_PLACEHOLDER: string
			/**
			 * V​a​l​u​e​ ​i​s​ ​n​o​t​ ​a​ ​v​a​l​i​d​ ​l​o​c​a​l​e​ ​c​o​d​e
			 */
			MSG_NOT_A_VALID_LOCALE_CODE: string
			/**
			 * D​a​t​e​ ​e​x​a​m​p​l​e​ ​:​ ​{​d​a​t​e​}
			 * @param {string} date
			 */
			MSG_DATE_EXAMPLE: RequiredParams<'date'>
			/**
			 * M​a​r​k​d​o​w​n​ ​:​ ​{​d​a​t​e​}
			 * @param {string} date
			 */
			MSG_MARKDWON_EXAMPLE: RequiredParams<'date'>
		}
		suggestModal: {
			/**
			 * S​e​l​e​c​t​ ​d​a​t​e​ ​f​o​r​m​a​t
			 */
			TITLE: string
			/**
			 * D​a​t​e​ ​t​o​ ​i​n​s​e​r​t
			 */
			BUTTON_INSERT_LABEL: string
			/**
			 * I​n​s​e​r​t
			 */
			BUTTON_INSERT: string
			/**
			 * C​l​o​s​e​ ​d​i​a​l​o​g​ ​a​n​d​ ​i​n​s​e​r​t​ ​d​a​t​e
			 */
			BUTTON_INSERT_TOOLTIP: string
			/**
			 * C​h​e​c​k​ ​t​o​ ​i​n​s​e​r​t​ ​d​a​t​e​ ​a​s​ ​l​i​n​k​ ​t​o​ ​t​h​e​ ​d​a​i​l​y​ ​n​o​t​e
			 */
			SETTING_DAILY_DESC: string
			/**
			 * D​a​t​e​ ​f​o​r​m​a​t
			 */
			SETTING_FORMAT_NAME: string
			/**
			 * U​s​e​r​ ​d​a​t​e​ ​f​o​r​m​a​t​ ​t​o​ ​u​s​e
			 */
			SETTING_FORMAT_DESC: string
			/**
			 * L​o​c​a​l​e
			 */
			SETTING_LOCALE_NAME: string
			/**
			 * U​s​e​d​ ​f​o​r​ ​g​e​n​e​r​i​c​ ​d​a​t​e​ ​f​o​r​m​a​t​s​ ​(​@​s​h​o​r​t​,​ ​@​l​o​n​g​.​.​)
			 */
			SETTING_LOCALE_DESC: string
		}
	}
}

export type TranslationFunctions = {
	/**
	 * Hi {name}! Please leave a star if you like this project: https://github.com/ivanhofer/typesafe-i18n
	 */
	HI: (arg: { name: string }) => LocalizedString
	utils: {
		intl: {
			/**
			 * {language} in {region}
			 */
			localeDescriptionWithRegion: (arg: { language: string, region: string }) => LocalizedString
			/**
			 * {language} using script {script}
			 */
			localeDescriptionWithScript: (arg: { language: string, script: string }) => LocalizedString
			/**
			 * {language} in {region} using script {script}
			 */
			localeDescriptionWithRegionAndScript: (arg: { language: string, region: string, script: string }) => LocalizedString
		}
	}
	commands: {
		/**
		 * Insert the current date
		 */
		INSERT_CURRENT_DATE: () => LocalizedString
		/**
		 * Parse and format with settings
		 */
		PARSE_DATE: () => LocalizedString
		/**
		 * Parse and format as link
		 */
		PARSE_DATE_AS_LINK: () => LocalizedString
		/**
		 * Parse and format as plain text
		 */
		PARSE_DATE_AS_TEXT: () => LocalizedString
		/**
		 * Parse and format with user format
		 */
		PARSE_AND_FORMAT_USER: () => LocalizedString
		/**
		 * Parse and format with locale
		 */
		PARSE_AND_FORMAT_LOCALE: () => LocalizedString
		/**
		 * Parse and show format dialog...
		 */
		PARSE_AND_FORMAT_DIALOG: () => LocalizedString
	}
	notifications: {
		/**
		 * International Dates : user interface language changed to **{locale}**
		 */
		UI_LOCALE_CHANGED: (arg: { locale: unknown }) => LocalizedString
		/**
		 * Settings loaded
		 */
		SETTINGS_LOADED: () => LocalizedString
		/**
		 * Text '{text}' wird nicht als Datum erkannt
		 */
		NOT_A_DATE: (arg: { text: string }) => LocalizedString
	}
	modals: {
		date_format: {
			/**
			 * Personnalized date format
			 */
			TITLE_PERSONNALIZED_DATE_FORMAT: () => LocalizedString
			/**
			 * Date options
			 */
			TITLE_DATE_OPTIONS: () => LocalizedString
			/**
			 * Date style
			 */
			SETTING_DATE_STYLE_NAME: () => LocalizedString
			/**
			 * Date style
			 */
			SETTING_DATE_STYLE_DESC: () => LocalizedString
			/**
			 * Year part
			 */
			SETTING_YEAR_PART_NAME: () => LocalizedString
			/**
			 * Width of year part
			 */
			SETTING_YEAR_PART_DESC: () => LocalizedString
			/**
			 * Month part
			 */
			SETTING_MONTH_PART_NAME: () => LocalizedString
			/**
			 * Width of month part
			 */
			SETTING_MONTH_PART_DESC: () => LocalizedString
			/**
			 * Day in month part
			 */
			SETTING_DAY_IN_MONTH_PART_NAME: () => LocalizedString
			/**
			 * Width of day in month part
			 */
			SETTING_DAY_IN_MONTH_PART_DESC: () => LocalizedString
			/**
			 * Weekday
			 */
			SETTING_DAY_OF_WEEK_PART_NAME: () => LocalizedString
			/**
			 * Style of weekday
			 */
			SETTING_DAY_OF_WEEK_PART_DESC: () => LocalizedString
			/**
			 * Description
			 */
			SETTING_DESCRIPTION_NAME: () => LocalizedString
			/**
			 * Description of user format
			 */
			SETTING_DESCRIPTION_DESC: () => LocalizedString
			/**
			 * Enter description...
			 */
			SETTING_DESCRIPTION_PLACEHOLDER: () => LocalizedString
			/**
			 * Locale
			 */
			SETTING_LOCALE_NAME: () => LocalizedString
			/**
			 * Locale used for formatting
			 */
			SETTING_LOCALE_DESC: () => LocalizedString
			/**
			 * Enter code of locale (like en or en-GB)...
			 */
			SETTING_LOCALE_PLACEHOLDER: () => LocalizedString
			/**
			 * Name
			 */
			SETTING_NAME_NAME: () => LocalizedString
			/**
			 * Used to select the format
			 */
			SETTING_NAME_DESC: () => LocalizedString
			/**
			 * Enter format name...
			 */
			SETTING_NAME_PLACEHOLDER: () => LocalizedString
			/**
			 * Value is not a valid locale code
			 */
			MSG_NOT_A_VALID_LOCALE_CODE: () => LocalizedString
			/**
			 * Date example : {date}
			 */
			MSG_DATE_EXAMPLE: (arg: { date: string }) => LocalizedString
			/**
			 * Markdown : {date}
			 */
			MSG_MARKDWON_EXAMPLE: (arg: { date: string }) => LocalizedString
		}
		suggestModal: {
			/**
			 * Select date format
			 */
			TITLE: () => LocalizedString
			/**
			 * Date to insert
			 */
			BUTTON_INSERT_LABEL: () => LocalizedString
			/**
			 * Insert
			 */
			BUTTON_INSERT: () => LocalizedString
			/**
			 * Close dialog and insert date
			 */
			BUTTON_INSERT_TOOLTIP: () => LocalizedString
			/**
			 * Check to insert date as link to the daily note
			 */
			SETTING_DAILY_DESC: () => LocalizedString
			/**
			 * Date format
			 */
			SETTING_FORMAT_NAME: () => LocalizedString
			/**
			 * User date format to use
			 */
			SETTING_FORMAT_DESC: () => LocalizedString
			/**
			 * Locale
			 */
			SETTING_LOCALE_NAME: () => LocalizedString
			/**
			 * Used for generic date formats (@short, @long..)
			 */
			SETTING_LOCALE_DESC: () => LocalizedString
		}
	}
}

export type Formatters = {}
